# Generated by Django 4.1.4 on 2023-01-02 15:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auther_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiefEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('family', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
            ],
        ),
        migrations.AlterField(
            model_name='auther',
            name='age',
            field=models.IntegerField(default=0, verbose_name='سن'),
        ),
        migrations.AlterField(
            model_name='auther',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='auther',
            name='family',
            field=models.CharField(max_length=30, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='auther',
            name='image_name',
            field=models.CharField(default='nophoto.jpg', max_length=200, verbose_name='نام تصویر'),
        ),
        migrations.AlterField(
            model_name='auther',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='auther',
            name='name',
            field=models.CharField(max_length=30, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='auther',
            name='register_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت نام'),
        ),
        migrations.AlterField(
            model_name='auther',
            name='sulg',
            field=models.SlugField(max_length=100, verbose_name='url آدرس'),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('title', models.CharField(max_length=100, verbose_name='نام انتشارات')),
                ('cheifEditor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.chiefeditor', verbose_name='سردبیر')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=300, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(max_length=100, verbose_name='url آدرس')),
                ('article_text', models.TextField(verbose_name='عنوان اصلی')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیر فعال')),
                ('status', models.CharField(choices=[('Draft', 'پیش نویس'), ('Publish', 'منتشر شده')], max_length=40, verbose_name='وضعیت')),
                ('auther', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.auther', verbose_name='نوسینده')),
                ('publication', models.ManyToManyField(to='blog.publication', verbose_name='انتشارات/سردبیر')),
            ],
        ),
    ]
