# Generated by Django 4.1.4 on 2023-01-02 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_chiefeditor_alter_auther_age_alter_auther_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AlterModelOptions(
            name='auther',
            options={'verbose_name': 'نویسنده', 'verbose_name_plural': 'نویسندگان'},
        ),
        migrations.AlterModelOptions(
            name='chiefeditor',
            options={'verbose_name': 'سردبیر', 'verbose_name_plural': 'سردبیر ها'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'نشریه', 'verbose_name_plural': 'نشریات'},
        ),
    ]
